### ISSUE TITLE
<a href> doesn't work on line 211 (page.html)

### ISSUE THREAD

**Issue by MrLuit** [TrumpTracker/trumptracker.github.io#61]
See https://github.com/TrumpTracker/trumptracker.github.io/blob/master/_layouts/page.html#L211, it just outputs `<a href>` for some reason. You can test it by searching something in the upper bar, and clicking one of the categories.

**Comment by VirenMohindra** [comment]
Added `a` tags and citation later on and didn't implement it in main nav search. Will probably need help -- but I do like the list of the main search being clean and then going in depth when you search below. Main source **should** work though.

**Comment by MrLuit** [comment]
Fixed it temporarily with 6f68b32e9bbfa1ca98f90bad4461e34f9d13aa3f , when citation is fully implemented it can be re-added with the right vars

**Comment by VirenMohindra** [comment]
We need the link! That's the main source

**Comment by MrLuit** [comment]
But there's no main source anymore

**Comment by VirenMohindra** [comment]
There is? It's still in the scheme afaik

**Comment by MrLuit** [comment]
There's no link property under each section in the data.yaml right? It's removed because each policy has its own source now.

BTW, I only removed the header a href, not the actually source a href. You can still click each policy but you can't click a header anymore.

**Comment by VirenMohindra** [comment]
You're right, I got confused.

When I looked at the commit changes from my phone I thought you edited the sources for each policy, not the main one.

```
            text: 'Propose a Constitutional Amendment to impose term limits on all members of Congress'
            status: notStarted
            citations:
              - ''
              - ''
            comments: 'https://redd.it/5d4r8m'
            source: 'http://www.npr.org/2016/11/09/501451368/here-is-what-donald-trump-wants-to-do-in-his-first-100-days'
```
